[package]
name = "time-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
dioxus = { git = "https://github.com/DioxusLabs/dioxus", features = [
    "desktop",
] }
tokio = { version = "1.36.0", features = ["time"] }
